version: 1
formatters:
  simple:
    format: "[%(asctime)s][%(threadName)s][%(levelname)-5s][%(name)s.%(funcName)s] - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
# external lib
loggers:
  keras:
    level: DEBUG
  injector:
    level: INFO
  invoker:
    level: INFO
root:
  level: DEBUG
  handlers:
    - console
disable_existing_loggers: false
